# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/ModularMonolith

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryEndpoint: 'classifiedads'
  dockerComposeFile: 'src/ModularMonolith/docker-compose.yml'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: SonarCloud
  displayName: SonarCloud
  jobs:  
  - job: SonarCloud
    displayName: SonarCloud
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'phongnguyend'
        scannerMode: 'MSBuild'
        projectKey: 'Practical.CleanArchitecture'
        projectName: 'Practical.CleanArchitecture'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'src/ModularMonolith/ClassifiedAds.ModularMonolith.sln'
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

- stage: WhiteSourceBolt
  displayName: Build and Run WhiteSource Bolt
  jobs:  
  - job: WhiteSourceBolt
    displayName: Build and Run WhiteSource Bolt
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'src/ModularMonolith/ClassifiedAds.ModularMonolith.sln'
    - task: WhiteSource Bolt@20
      inputs:
        cwd: 'src/ModularMonolith/'

- stage: DotNetBuild
  displayName: .Net Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: 'build'
          arguments: '--configuration Release'
          workingDirectory: 'src/ModularMonolith'
      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: |
            src/ModularMonolith/ClassifiedAds.BackgroundServer/*.csproj
            src/ModularMonolith/ClassifiedAds.Migrator/*.csproj
            src/ModularMonolith/ClassifiedAds.NotificationServer/*.csproj
            src/ModularMonolith/ClassifiedAds.WebAPI/*.csproj
            src/ModularMonolith/ClassifiedAds.IdentityServer/*.csproj
          arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'ModularMonolith'
          publishLocation: 'Container'

- stage: DockerBuild
  displayName: Build and Push Docker Images
  jobs:  
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      displayName: Build services
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: $(dockerRegistryEndpoint)
        dockerComposeFile: $(dockerComposeFile)
        action: 'Build services'
        projectName: $(Build.Repository.Name)
        qualifyImageNames: true
        additionalImageTags: $(Build.BuildId)
    - task: DockerCompose@0
      displayName: Push services
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: $(dockerRegistryEndpoint)
        dockerComposeFile: $(dockerComposeFile)
        action: 'Push services'
        projectName: $(Build.Repository.Name)
        qualifyImageNames: true
        additionalImageTags: $(Build.BuildId)