# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/Monolith

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryEndpoint: 'classifiedads'
  dockerComposeFile: 'src/Monolith/docker-compose.yml'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: SonarCloud
  displayName: SonarCloud
  jobs:  
  - job: SonarCloud
    displayName: SonarCloud
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'phongnguyend'
        scannerMode: 'MSBuild'
        projectKey: 'Practical.CleanArchitecture'
        projectName: 'Practical.CleanArchitecture'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'src/Monolith/ClassifiedAds.Monolith.slnx'
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

- stage: WhiteSourceBolt
  displayName: Build and Run WhiteSource Bolt
  jobs:  
  - job: WhiteSourceBolt
    displayName: Build and Run WhiteSource Bolt
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'src/Monolith/ClassifiedAds.Monolith.slnx'
    - task: WhiteSource Bolt@20
      inputs:
        cwd: 'src/Monolith/'

- stage: DotNetBuild
  displayName: .Net Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: UseDotNet@2
        displayName: Use .Net 6.0.x
        inputs:
          packageType: 'sdk'
          version: '6.0.x'
      - task: DotNetCoreCLI@2
        displayName: dotnet restore
        inputs:
          command: 'restore'
          projects: 'src/Monolith/ClassifiedAds.Monolith.slnx'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: dotnet list package --vulnerable
        inputs:
          command: 'custom'
          custom: 'list'
          arguments: 'package --vulnerable'
          workingDirectory: 'src/Monolith'
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: 'build'
          arguments: '--configuration Release'
          workingDirectory: 'src/Monolith'
      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: 'test'
          projects: |
            src/Monolith/ClassifiedAds.ArchTests/*.csproj
            src/Monolith/ClassifiedAds.ContractTests/*.csproj
            src/Monolith/ClassifiedAds.UnitTests/*.csproj
          arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura "/p:Include=\"[ClassifiedAds.Application]*,[ClassifiedAds.Domain]*\""'
      - task: PublishCodeCoverageResults@2
        displayName: 'Publish Code Coverage'
        inputs:
          summaryFileLocation: '$(Build.SourcesDirectory)/**/*.cobertura.xml'
      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: |
            src/Monolith/ClassifiedAds.Background/*.csproj
            src/Monolith/ClassifiedAds.Migrator/*.csproj
            src/Monolith/ClassifiedAds.WebAPI/*.csproj
            src/Monolith/ClassifiedAds.IdentityServer/*.csproj
            src/Monolith/ClassifiedAds.WebMVC/*.csproj
            src/Monolith/ClassifiedAds.BlazorServerSide/*.csproj
            src/Monolith/ClassifiedAds.BlazorWebAssembly/*.csproj
          arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'Monolith'
          publishLocation: 'Container'

- stage: DockerBuild
  displayName: Build and Push Docker Images
  jobs:  
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      displayName: Build services
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: $(dockerRegistryEndpoint)
        dockerComposeFile: $(dockerComposeFile)
        action: 'Build services'
        projectName: $(Build.Repository.Name)
        qualifyImageNames: true
        additionalImageTags: $(Build.BuildId)
    - task: DockerCompose@0
      displayName: Push services
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: $(dockerRegistryEndpoint)
        dockerComposeFile: $(dockerComposeFile)
        action: 'Push services'
        projectName: $(Build.Repository.Name)
        qualifyImageNames: true
        additionalImageTags: $(Build.BuildId)

- stage: Octopus
  displayName: 'Octopus: Pack and Push Nuget Packages'
  jobs:  
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: CmdLine@2
      displayName: dotnet tool install Octopus.DotNet.Cli --global
      inputs:
        script: 'dotnet tool install Octopus.DotNet.Cli --global'
    - task: DotNetCoreCLI@2
      displayName: dotnet restore
      inputs:
        command: 'restore'
        projects: 'src/Monolith/ClassifiedAds.Monolith.slnx'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        command: 'build'
        arguments: '--configuration Release'
        workingDirectory: 'src/Monolith'
    - task: DotNetCoreCLI@2
      displayName: dotnet publish
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: |
          src/Monolith/ClassifiedAds.Background/*.csproj
          src/Monolith/ClassifiedAds.Migrator/*.csproj
          src/Monolith/ClassifiedAds.WebAPI/*.csproj
          src/Monolith/ClassifiedAds.IdentityServer/*.csproj
          src/Monolith/ClassifiedAds.WebMVC/*.csproj
          src/Monolith/ClassifiedAds.BlazorServerSide/*.csproj
          src/Monolith/ClassifiedAds.BlazorWebAssembly/*.csproj
        arguments: '--configuration Release -p:Version=1.0.0-$(Build.BuildNumber) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: false

    - task: CmdLine@2
      displayName: dotnet octo pack
      inputs:
        script: |
          dotnet octo pack --version=1.0.0-$(Build.BuildNumber) --outFolder=$(Build.ArtifactStagingDirectory) --overwrite --id=ClassifiedAds.Background --basePath=$(Build.ArtifactStagingDirectory)/ClassifiedAds.Background
          dotnet octo pack --version=1.0.0-$(Build.BuildNumber) --outFolder=$(Build.ArtifactStagingDirectory) --overwrite --id=ClassifiedAds.Migrator --basePath=$(Build.ArtifactStagingDirectory)/ClassifiedAds.Migrator
          dotnet octo pack --version=1.0.0-$(Build.BuildNumber) --outFolder=$(Build.ArtifactStagingDirectory) --overwrite --id=ClassifiedAds.WebAPI --basePath=$(Build.ArtifactStagingDirectory)/ClassifiedAds.WebAPI
          dotnet octo pack --version=1.0.0-$(Build.BuildNumber) --outFolder=$(Build.ArtifactStagingDirectory) --overwrite --id=ClassifiedAds.BlazorServerSide --basePath=$(Build.ArtifactStagingDirectory)/ClassifiedAds.BlazorServerSide
          dotnet octo pack --version=1.0.0-$(Build.BuildNumber) --outFolder=$(Build.ArtifactStagingDirectory) --overwrite --id=ClassifiedAds.BlazorWebAssembly --basePath=$(Build.ArtifactStagingDirectory)/ClassifiedAds.BlazorWebAssembly
          dotnet octo pack --version=1.0.0-$(Build.BuildNumber) --outFolder=$(Build.ArtifactStagingDirectory) --overwrite --id=ClassifiedAds.IdentityServer --basePath=$(Build.ArtifactStagingDirectory)/ClassifiedAds.IdentityServer
          dotnet octo pack --version=1.0.0-$(Build.BuildNumber) --outFolder=$(Build.ArtifactStagingDirectory) --overwrite --id=ClassifiedAds.WebMVC --basePath=$(Build.ArtifactStagingDirectory)/ClassifiedAds.WebMVC
    - task: DotNetCoreCLI@2
      displayName: dotnet nuget push
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: '649b11e9-9f40-41ae-bf73-6d93e3161e2c/24cbed38-cd60-4d56-bad6-7c5d18f75a60'