version: "3.6"
services:
    migrator:
        volumes:
            - D:\\ClassifiedAds.Monolith\\Logs\\Migrator:/ClassifiedAds.Monolith/logs
    identityserver:
        volumes:
            - D:\\ClassifiedAds.Monolith\\Logs\\IdentityServer:/ClassifiedAds.IdentityServer/logs
    webapi:
        volumes:
            - D:\\ClassifiedAds.Monolith\\Logs\\WebAPI:/ClassifiedAds.Monolith/logs
            - D:\\ClassifiedAds.Monolith\\Files:/files
    webmvc:
        volumes:
            - D:\\ClassifiedAds.Monolith\\Files:/files
            - D:\\ClassifiedAds.Monolith\\Logs\\WebMVC:/ClassifiedAds.Monolith/logs
    blazor:
        volumes:
            - D:\\ClassifiedAds.Monolith\\Logs\\BlazorServerSide:/ClassifiedAds.Monolith/logs
    background:
        volumes:
            - D:\\ClassifiedAds.Monolith\\Logs\\Background:/ClassifiedAds.Monolith/logs
    graphql:
        volumes:
            - D:\\ClassifiedAds.Monolith\\Logs\\GraphQL:/ClassifiedAds.Monolith/logs
