apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds.Microservices.Configuration;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true;Encrypt=False"
