apiVersion: v1
kind: ConfigMap
metadata:
  name: shared
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  IdentityServerAuthentication__Authority: "http://identityserver"
  IdentityServerAuthentication__RequireHttpsMetadata: "false"
  Services__AuditLog__Grpc: "https://auditlog-grpc"
  Services__Identity__Grpc: "https://identity-grpc"
  Services__Notification__Grpc: "https://notification-grpc"
