apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backgroundserver
  name: backgroundserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backgroundserver
  strategy: {}
  template:
    metadata:
      labels:
        app: backgroundserver
    spec:
      containers:
      - env:
        - name: CheckDependency__Enabled
          value: "true"
        - name: CheckDependency__Host
          value: migrator:80,rabbitmq:5672
        - name: NotificationServer__Endpoint
          value: http://notificationserver
        envFrom:
        - configMapRef:
            name: shared
        image: phongnguyend/classifiedads.backgroundserver
        name: backgroundserver
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
