apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webmvc
  name: webmvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webmvc
  strategy: {}
  template:
    metadata:
      labels:
        app: webmvc
    spec:
      containers:
      - env:
        - name: BackgroundServer__Endpoint
          value: http://backgroundserver
        - name: CheckDependency__Enabled
          value: "true"
        - name: CheckDependency__Host
          value: migrator:80
        - name: CookiePolicyOptions__IsEnabled
          value: "true"
        - name: CookiePolicyOptions__MinimumSameSitePolicy
          value: Lax
        - name: CookiePolicyOptions__Secure
          value: None
        - name: CurrentUrl
          value: http://host.docker.internal:9003
        - name: NotificationServer__Endpoint
          value: http://notificationserver
        - name: NotificationServer__PublicEndpoint
          value: http://localhost:9001
        - name: OpenIdConnect__Authority
          value: http://identityserver
        - name: OpenIdConnect__RequireHttpsMetadata
          value: "false"
        - name: ResourceServer__Endpoint
          value: http://webapi
        - name: ResourceServer__PublicEndpoint
          value: http://webapi
        envFrom:
        - configMapRef:
            name: shared
        image: phongnguyend/classifiedads.webmvc
        name: webmvc
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
