apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-product
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ConnectionStrings__ClassifiedAds: "Server={{ .Release.Name}}-db;Database=ClassifiedAds.Microservices;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
