version: "3.6"
services:
    db:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        ports:
            - "1434:1433"
        environment:
            SA_PASSWORD: "sqladmin123!@#"
            MSSQL_PID: "Developer"
            ACCEPT_EULA: "Y"
    rabbitmq:
        image: "rabbitmq:3-management"
        ports:
          - "5672:5672"
          - "15672:15672"
    mailhog:
        image: mailhog/mailhog
        ports: 
          - 1025:1025 # smtp server
          - 8025:8025 # web ui
    auditlog-api:
        image: classifiedads.services.auditlog.api
        build:
          context: .
          dockerfile: ./Services.AuditLog/ClassifiedAds.Services.AuditLog.Api/Dockerfile
        volumes:
            - D:\\ClassifiedAds.Microservices\\Logs\\AuditLog.Api:/ClassifiedAds.Microservices/logs
        depends_on:
          - db
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds.Microservices;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          IdentityServerAuthentication__Authority: "http://host.docker.internal:9000"
          IdentityServerAuthentication__RequireHttpsMetadata: "false"
          Services__AuditLog__Grpc: "https://auditlog-grpc"
          Services__Identity__Grpc: "https://identity-grpc"
          Services__Notification__Grpc: "https://notification-grpc"
    auditlog-grpc:
        image: classifiedads.services.auditlog.grpc
        build:
          context: .
          dockerfile: ./Services.AuditLog/ClassifiedAds.Services.AuditLog.Grpc/Dockerfile
        volumes:
            - D:\\ClassifiedAds.Microservices\\Logs\\AuditLog.Grpc:/ClassifiedAds.Microservices/logs
        depends_on:
          - db
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ASPNETCORE_URLS: "https://+"
          ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds.Microservices;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          Services__AuditLog__Grpc: "https://auditlog-grpc"
          Services__Identity__Grpc: "https://identity-grpc"
          Services__Notification__Grpc: "https://notification-grpc"
    identity-api:
        image: classifiedads.services.identity.api
        build:
          context: .
          dockerfile: ./Services.Identity/ClassifiedAds.Services.Identity.Api/Dockerfile
        volumes:
            - D:\\ClassifiedAds.Microservices\\Logs\\Identity.Api:/ClassifiedAds.Microservices/logs
        depends_on:
          - db
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds.Microservices;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          IdentityServerAuthentication__Authority: "http://host.docker.internal:9000"
          IdentityServerAuthentication__RequireHttpsMetadata: "false"
          Services__AuditLog__Grpc: "https://auditlog-grpc"
          Services__Identity__Grpc: "https://identity-grpc"
          Services__Notification__Grpc: "https://notification-grpc"
    identity-authserver:
        image: classifiedads.services.identity.authserver
        build:
          context: .
          dockerfile: ./Services.Identity/ClassifiedAds.Services.Identity.AuthServer/Dockerfile
        ports:
          - "9000:80"
        volumes:
            - D:\\ClassifiedAds.Microservices\\Logs\\Identity.AuthServer:/ClassifiedAds.Microservices/logs
        depends_on:
          - db
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds.Microservices;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          CookiePolicyOptions__IsEnabled: "true"
          CookiePolicyOptions__MinimumSameSitePolicy: "Lax"
          CookiePolicyOptions__Secure: "None"
          MessageBroker__Provider: "RabbitMQ"
          MessageBroker__RabbitMQ__HostName: "rabbitmq"
          Services__AuditLog__Grpc: "https://auditlog-grpc"
          Services__Identity__Grpc: "https://identity-grpc"
          Services__Notification__Grpc: "https://notification-grpc"
    identity-grpc:
        image: classifiedads.services.identity.grpc
        build:
          context: .
          dockerfile: ./Services.Identity/ClassifiedAds.Services.Identity.Grpc/Dockerfile
        volumes:
            - D:\\ClassifiedAds.Microservices\\Logs\\Identity.Grpc:/ClassifiedAds.Microservices/logs
        depends_on:
          - db
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ASPNETCORE_URLS: "https://+"
          ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds.Microservices;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          Services__AuditLog__Grpc: "https://auditlog-grpc"
          Services__Identity__Grpc: "https://identity-grpc"
          Services__Notification__Grpc: "https://notification-grpc"
    notification-api:
        image: classifiedads.services.notification.api
        build:
          context: .
          dockerfile: ./Services.Notification/ClassifiedAds.Services.Notification.Api/Dockerfile
        volumes:
            - D:\\ClassifiedAds.Microservices\\Logs\\Notification.Api:/ClassifiedAds.Microservices/logs
        depends_on:
          - db
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds.Microservices;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          IdentityServerAuthentication__Authority: "http://host.docker.internal:9000"
          IdentityServerAuthentication__RequireHttpsMetadata: "false"
          MessageBroker__Provider: "RabbitMQ"
          MessageBroker__RabbitMQ__HostName: "rabbitmq"
          Services__AuditLog__Grpc: "https://auditlog-grpc"
          Services__Identity__Grpc: "https://identity-grpc"
          Services__Notification__Grpc: "https://notification-grpc"
    notification-background:
        image: classifiedads.services.notification.background
        build:
          context: .
          dockerfile: ./Services.Notification/ClassifiedAds.Services.Notification.Background/Dockerfile
        volumes:
            - D:\\ClassifiedAds.Microservices\\Logs\\Notification.Background:/ClassifiedAds.Microservices/logs
        depends_on:
          - db
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds.Microservices;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          IdentityServerAuthentication__Authority: "http://host.docker.internal:9000"
          IdentityServerAuthentication__RequireHttpsMetadata: "false"
          MessageBroker__Provider: "RabbitMQ"
          MessageBroker__RabbitMQ__HostName: "rabbitmq"
          Notification__Email__Provider: "SmtpClient"
          Notification__Email__SmtpClient__Host: "mailhog"
          Notification__Email__SmtpClient__Port: "1025"
          Notification__Sms__Provider: "Fake"
          Notification__Sms__Twilio__AccountSId: ""
          Notification__Sms__Twilio__AuthToken: ""
          Notification__Sms__Twilio__FromNumber: ""
          Services__AuditLog__Grpc: "https://auditlog-grpc"
          Services__Identity__Grpc: "https://identity-grpc"
          Services__Notification__Grpc: "https://notification-grpc"
    notification-grpc:
        image: classifiedads.services.notification.grpc
        build:
          context: .
          dockerfile: ./Services.Notification/ClassifiedAds.Services.Notification.Grpc/Dockerfile
        volumes:
            - D:\\ClassifiedAds.Microservices\\Logs\\Notification.Grpc:/ClassifiedAds.Microservices/logs
        depends_on:
          - db
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ASPNETCORE_URLS: "https://+"
          ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds.Microservices;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          MessageBroker__Provider: "RabbitMQ"
          MessageBroker__RabbitMQ__HostName: "rabbitmq"
          Services__AuditLog__Grpc: "https://auditlog-grpc"
          Services__Identity__Grpc: "https://identity-grpc"
          Services__Notification__Grpc: "https://notification-grpc"
    product-api:
        image: classifiedads.services.product.api
        build:
          context: .
          dockerfile: ./Services.Product/ClassifiedAds.Services.Product.Api/Dockerfile
        volumes:
            - D:\\ClassifiedAds.Microservices\\Logs\\Product.Api:/ClassifiedAds.Microservices/logs
        depends_on:
          - db
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds.Microservices;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          IdentityServerAuthentication__Authority: "http://host.docker.internal:9000"
          IdentityServerAuthentication__RequireHttpsMetadata: "false"
          Services__AuditLog__Grpc: "https://auditlog-grpc"
          Services__Identity__Grpc: "https://identity-grpc"
          Services__Notification__Grpc: "https://notification-grpc"
    storage-api:
        image: classifiedads.services.storage.api
        build:
          context: .
          dockerfile: ./Services.Storage/ClassifiedAds.Services.Storage.Api/Dockerfile
        volumes:
            - D:\\ClassifiedAds.Microservices\\Logs\\Storage.Api:/ClassifiedAds.Microservices/logs
            - D:\\ClassifiedAds.Microservices\\Files:/files
        depends_on:
          - db
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds.Microservices;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          IdentityServerAuthentication__Authority: "http://host.docker.internal:9000"
          IdentityServerAuthentication__RequireHttpsMetadata: "false"
          MessageBroker__Provider: "RabbitMQ"
          MessageBroker__RabbitMQ__HostName: "rabbitmq"
          Storage__Provider: "Local"
          Storage__Local__Path: "/files"
          Services__AuditLog__Grpc: "https://auditlog-grpc"
          Services__Identity__Grpc: "https://identity-grpc"
          Services__Notification__Grpc: "https://notification-grpc"
    ocelot:
        image: classifiedads.gateways.ocelot
        build:
          context: .
          dockerfile: ./Gateways.Ocelot/ClassifiedAds.Gateways.Ocelot/Dockerfile
        ports:
            - "9002:80"
        volumes:
            - D:\\ClassifiedAds.Microservices\\Logs\\Ocelot:/ClassifiedAds.Microservices/logs
        depends_on:
          - db
        environment:
          ASPNETCORE_ENVIRONMENT: "Docker"
