version: "3.6"
services:
    identityserver:
        build:
          context: .
          dockerfile: ./ClassifiedAds.IdentityServer/Dockerfile
        ports:
            - "9000:80"
        volumes:
            - E:\\ClassifiedAds.Projects\\Logs\\IdentityServer:/ClassifiedAds.Projects/logs
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=host.docker.internal;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
    notificationserver:
        build:
          context: .
          dockerfile: ./ClassifiedAds.NotificationServer/Dockerfile
        ports:
            - "9001:80"
        volumes:
            - E:\\ClassifiedAds.Projects\\Logs\\NotificationServer:/ClassifiedAds.Projects/logs
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=host.docker.internal;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
    webapi:
        build:
          context: .
          dockerfile: ./ClassifiedAds.WebAPI/Dockerfile
        ports:
            - "9002:80"
        volumes:
            - E:\\ClassifiedAds.Projects\\Logs\\WebAPI:/ClassifiedAds.Projects/logs
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=host.docker.internal;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          IdentityServerAuthentication__Authority: "http://host.docker.internal:9000"
          IdentityServerAuthentication__RequireHttpsMetadata: "false"
    webmvc:
        build:
          context: .
          dockerfile: ./ClassifiedAds.WebMVC/Dockerfile
        ports:
            - "9003:80"
        volumes:
            - E:\\ClassifiedAds.Projects\\Files:/files
            - E:\\ClassifiedAds.Projects\\Logs\\WebMVC:/ClassifiedAds.Projects/logs
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=host.docker.internal;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          OpenIdConnect__Authority: "http://host.docker.internal:9000"
          OpenIdConnect__RequireHttpsMetadata: "false"
          ResourceServer__Endpoint: "http://webapi"
          NotificationServer__Endpoint: "http://host.docker.internal:9001"
          CurrentUrl: "http://localhost:80"
          Storage__Provider: "Local"
          Storage__Local__Path: "/files"
          Storage__Azure__ConnectionString: "DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;EndpointSuffix=core.windows.net"
          Storage__Azure__Container: "classifiedadds"
          Storage__Amazon__AccessKeyID: "xxx"
          Storage__Amazon__SecretAccessKey: "xxx"
          Storage__Amazon__BucketName: "classifiedadds"
          Storage__Amazon__RegionEndpoint: "ap-southeast-1"
          MessageBroker__Provider: "RabbitMQ"
          MessageBroker__RabbitMQ__HostName: "host.docker.internal"
          MessageBroker__RabbitMQ__UserName: "guest"
          MessageBroker__RabbitMQ__Password: "guest"
          MessageBroker__RabbitMQ__ExchangeName: "amq.direct"
          MessageBroker__RabbitMQ__RoutingKey_FileUploaded: "classifiedadds_fileuploaded"
          MessageBroker__RabbitMQ__RoutingKey_FileDeleted: "classifiedadds_filedeleted"
          MessageBroker__RabbitMQ__QueueName_FileUploaded: "classifiedadds_fileuploaded"
          MessageBroker__RabbitMQ__QueueName_FileDeleted: "classifiedadds_filedeleted"
          MessageBroker__Kafka__BootstrapServers: "host.docker.internal:9092"
          MessageBroker__Kafka__Topic_FileUploaded: "classifiedadds_fileuploaded"
          MessageBroker__Kafka__Topic_FileDeleted: "classifiedadds_filedeleted"
          MessageBroker__Kafka__GroupId: "classified"
          MessageBroker__AzureQueue__ConnectionString: "DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;EndpointSuffix=core.windows.net"
          MessageBroker__AzureQueue__QueueName_FileUploaded: "classifiedadds-fileuploaded"
          MessageBroker__AzureQueue__QueueName_FileDeleted: "classifiedadds-filedeleted"
          MessageBroker__AzureServiceBus__ConnectionString: "Endpoint=sb://xxx.servicebus.windows.net/;SharedAccessKeyName=xxx;SharedAccessKey=xxx"
          MessageBroker__AzureServiceBus__QueueName_FileUploaded: "classifiedadds_fileuploaded"
          MessageBroker__AzureServiceBus__QueueName_FileDeleted: "classifiedadds_filedeleted"
    backgroundservices:
        build:
          context: .
          dockerfile: ./ClassifiedAds.BackgroundServices/Dockerfile
        ports:
            - "9004:80"
        volumes:
            - E:\\ClassifiedAds.Projects\\Logs\\BackgroundServices:/ClassifiedAds.Projects/logs
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=host.docker.internal;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          NotificationServer__Endpoint: "http://notificationserver"
    grpc:
        build:
          context: .
          dockerfile: ./ClassifiedAds.GRPC/Dockerfile
        ports:
            - "9005:443"
        volumes:
            - E:\\ClassifiedAds.Projects\\Logs\\GRPC:/ClassifiedAds.Projects/logs
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ASPNETCORE_URLS: "https://+"
          ConnectionStrings__ClassifiedAds: "Server=host.docker.internal;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
    graphql:
        build:
          context: .
          dockerfile: ./ClassifiedAds.GraphQL/Dockerfile
        ports:
            - "9006:80"
        volumes:
            - E:\\ClassifiedAds.Projects\\Logs\\GraphQL:/ClassifiedAds.Projects/logs
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=host.docker.internal;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          GrpcService__Endpoint: "https://grpc"
    ocelot:
        build:
          context: .
          dockerfile: ./ClassifiedAds.Ocelot/Dockerfile
        ports:
            - "9007:80"
        volumes:
            - E:\\ClassifiedAds.Projects\\Logs\\Ocelot:/ClassifiedAds.Projects/logs
        environment:
          ASPNETCORE_ENVIRONMENT: "Docker"
          ConnectionStrings__ClassifiedAds: "Server=host.docker.internal;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
