name: .Net Build Microservices

on:
  push:
    paths: 
      - 'src/Microservices/**'
  pull_request:
    paths: 
      - 'src/Microservices/**'

jobs:
  build:

    defaults: 
      run:
        working-directory: src/Microservices
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.102

    - name: Build
      run: dotnet build --configuration Release 
    
    - name: Publish AuditLog.Api
      run: dotnet publish Services.AuditLog/ClassifiedAds.Services.AuditLog.Api/*.csproj --configuration Release

    - name: Publish AuditLog.Grpc
      run: dotnet publish Services.AuditLog/ClassifiedAds.Services.AuditLog.Grpc/*.csproj --configuration Release

    - name: Publish Identity.Api
      run: dotnet publish Services.Identity/ClassifiedAds.Services.Identity.Api/*.csproj --configuration Release

    - name: Publish Identity.Grpc
      run: dotnet publish Services.Identity/ClassifiedAds.Services.Identity.Grpc/*.csproj --configuration Release

    - name: Publish Notification.Api
      run: dotnet publish Services.Notification/ClassifiedAds.Services.Notification.Api/*.csproj --configuration Release
 
    - name: Publish Notification.Background
      run: dotnet publish Services.Notification/ClassifiedAds.Services.Notification.Background/*.csproj --configuration Release

    - name: Publish Notification.Grpc
      run: dotnet publish Services.Notification/ClassifiedAds.Services.Notification.Grpc/*.csproj --configuration Release

    - name: Publish Product.Api
      run: dotnet publish Services.Product/ClassifiedAds.Services.Product.Api/*.csproj --configuration Release

    - name: Publish Storage.Api
      run: dotnet publish Services.Storage/ClassifiedAds.Services.Storage.Api/*.csproj --configuration Release

    - name: Publish Gateways.WebAPI
      run: dotnet publish Gateways.WebAPI/ClassifiedAds.Gateways.WebAPI/*.csproj --configuration Release

    - name: Upload ClassifiedAds.Services.AuditLog.Api
      uses: actions/upload-artifact@v4
      with:
        name: ClassifiedAds.Services.AuditLog.Api
        path: src/Microservices/Services.AuditLog/ClassifiedAds.Services.AuditLog.Api/bin/Release/net8.0/publish

    - name: Upload ClassifiedAds.Services.AuditLog.Grpc
      uses: actions/upload-artifact@v4
      with:
        name: ClassifiedAds.Services.AuditLog.Grpc
        path: src/Microservices/Services.AuditLog/ClassifiedAds.Services.AuditLog.Grpc/bin/Release/net8.0/publish

    - name: Upload ClassifiedAds.Services.Identity.Api
      uses: actions/upload-artifact@v4
      with:
        name: ClassifiedAds.Services.Identity.Api
        path: src/Microservices/Services.Identity/ClassifiedAds.Services.Identity.Api/bin/Release/net8.0/publish

    - name: Upload ClassifiedAds.Services.Identity.Grpc
      uses: actions/upload-artifact@v4
      with:
        name: ClassifiedAds.Services.Identity.Grpc
        path: src/Microservices/Services.Identity/ClassifiedAds.Services.Identity.Grpc/bin/Release/net8.0/publish

    - name: Upload ClassifiedAds.Services.Notification.Api
      uses: actions/upload-artifact@v4
      with:
        name: ClassifiedAds.Services.Notification.Api
        path: src/Microservices/Services.Notification/ClassifiedAds.Services.Notification.Api/bin/Release/net8.0/publish

    - name: Upload ClassifiedAds.Services.Notification.Background
      uses: actions/upload-artifact@v4
      with:
        name: ClassifiedAds.Services.Notification.Background
        path: src/Microservices/Services.Notification/ClassifiedAds.Services.Notification.Background/bin/Release/net8.0/publish

    - name: Upload ClassifiedAds.Services.Notification.Grpc
      uses: actions/upload-artifact@v4
      with:
        name: ClassifiedAds.Services.Notification.Grpc
        path: src/Microservices/Services.Notification/ClassifiedAds.Services.Notification.Grpc/bin/Release/net8.0/publish

    - name: Upload ClassifiedAds.Services.Product.Api
      uses: actions/upload-artifact@v4
      with:
        name: ClassifiedAds.Services.Product.Api
        path: src/Microservices/Services.Product/ClassifiedAds.Services.Product.Api/bin/Release/net8.0/publish

    - name: Upload ClassifiedAds.Services.Storage.Api
      uses: actions/upload-artifact@v4
      with:
        name: ClassifiedAds.Services.Storage.Api
        path: src/Microservices/Services.Storage/ClassifiedAds.Services.Storage.Api/bin/Release/net8.0/publish

    - name: Upload ClassifiedAds.Gateways.WebAPI
      uses: actions/upload-artifact@v4
      with:
        name: ClassifiedAds.Gateways.WebAPI
        path: src/Microservices/Gateways.WebAPI/ClassifiedAds.Gateways.WebAPI/bin/Release/net8.0/publish
