name: .Net Build Monolith

on:
  push:
    paths: 
      - 'src/Monolith/**'
  pull_request:
    paths: 
      - 'src/Monolith/**'

jobs:
  build:

    defaults: 
      run:
        working-directory: src/Monolith
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100
    
    - name: Build
      run: dotnet build --configuration Release 
    
    - name: Publish ClassifiedAds.BackgroundServer
      run: dotnet publish ClassifiedAds.BackgroundServer/*.csproj --configuration Release
 
    - name: Publish ClassifiedAds.GraphQL
      run: dotnet publish ClassifiedAds.GraphQL/*.csproj --configuration Release
      
    - name: Publish ClassifiedAds.Migrator
      run: dotnet publish ClassifiedAds.Migrator/*.csproj --configuration Release
 
    - name: Publish ClassifiedAds.WebAPI
      run: dotnet publish ClassifiedAds.WebAPI/*.csproj --configuration Release
      
    - name: Publish ClassifiedAds.WebMVC
      run: dotnet publish ClassifiedAds.WebMVC/*.csproj --configuration Release
      
    - name: Publish ClassifiedAds.BlazorServerSide
      run: dotnet publish ClassifiedAds.BlazorServerSide/*.csproj --configuration Release
      
    - name: Publish ClassifiedAds.BlazorWebAssembly
      run: dotnet publish ClassifiedAds.BlazorWebAssembly/*.csproj --configuration Release
      
    - name: Upload ClassifiedAds.BackgroundServer
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ClassifiedAds.BackgroundServer
        path: src/Monolith/ClassifiedAds.BackgroundServer/bin/Release/net8.0/publish
        
    - name: Upload ClassifiedAds.GraphQL
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ClassifiedAds.GraphQL
        path: src/Monolith/ClassifiedAds.GraphQL/bin/Release/net8.0/publish

    - name: Upload ClassifiedAds.Migrator
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ClassifiedAds.Migrator
        path: src/Monolith/ClassifiedAds.Migrator/bin/Release/net8.0/publish

    - name: Upload ClassifiedAds.WebAPI
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ClassifiedAds.WebAPI
        path: src/Monolith/ClassifiedAds.WebAPI/bin/Release/net8.0/publish
        
    - name: Upload ClassifiedAds.WebMVC
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ClassifiedAds.WebMVC
        path: src/Monolith/ClassifiedAds.WebMVC/bin/Release/net8.0/publish

    - name: Upload ClassifiedAds.BlazorServerSide
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ClassifiedAds.BlazorServerSide
        path: src/Monolith/ClassifiedAds.BlazorServerSide/bin/Release/net8.0/publish

    - name: Upload ClassifiedAds.BlazorWebAssembly
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ClassifiedAds.BlazorWebAssembly
        path: src/Monolith/ClassifiedAds.BlazorWebAssembly/bin/Release/net8.0/publish
