name: Build UI VueJs

on:
  push:
    paths:
      - "src/UIs/vuejs/**"
      - ".github/workflows/build-ui-vuejs.yml"
  pull_request:
    paths:
      - "src/UIs/vuejs/**"
      - ".github/workflows/build-ui-vuejs.yml"
  workflow_dispatch:
env:
  WORKING_DIRECTORY: ./src/UIs/vuejs/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "24"
      - run: npm install
        working-directory: ./src/UIs/vuejs/
      - run: npm run build
        working-directory: ./src/UIs/vuejs/
      - name: Upload VueJs
        uses: actions/upload-artifact@v4
        with:
          name: VueJs
          path: ./src/UIs/vuejs/dist
