name: Build UI Angular

on:
  push:
    paths:
      - "src/UIs/angular/**"
  pull_request:
    paths:
      - "src/UIs/angular/**"
env:
  WORKING_DIRECTORY: ./src/UIs/angular/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm install -g @angular/cli
      - run: npm install
        working-directory: ./src/UIs/angular/
      - run: npm audit --audit-level=critical
        working-directory: ./src/UIs/angular/
      - run: ng build
        working-directory: ./src/UIs/angular/
      - name: Upload Angular
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Angular
          path: ./src/UIs/angular/dist/angular
